### ISSUE TITLE
Not urgent: "Open in Visual Code" button does not work

### ISSUE THREAD

**Issue by CamKem** [sfx101/deck#112]
I just noticed the "Open in Visual Studio Code" button does not open the program.
MacOS operating system.

**Comment by nabad600** [comment]
Hello @CamKem, 
Thank you for your interest in DECK. Below is a list of the first option.

**1. Please make sure your terminal is responding to "code" commands.**
( Open Terminal in your system and go to any folder and type "code ." automatically open vscode )
![image](https://user-images.githubusercontent.com/67466982/200190301-05d797f3-cc03-4fb2-a305-9421d6fd5b5e.png)
    a.)If not, code command is ineffective.
            ![image](https://user-images.githubusercontent.com/67466982/200190446-abee6665-d8da-4fc3-8472-cdeb5be638ec.png)
    Then, Launch VS Code after that, then use Ctrl+Shift+P to access the Command Palette, and then type "shell 
     command" to locate the Shell Command: Install the PATH command's "code" command.
    ![image](https://user-images.githubusercontent.com/67466982/200190588-f24e159e-bfa2-4c53-a0af-e4445a2761f9.png)
    b.) Check the programme settings if the code command is functioning.

**2. Application Setting**
Launch the "DECK" programme
![image](https://user-images.githubusercontent.com/67466982/200190803-d2b9f378-d1a6-4eab-9111-ab735d12071b.png)

We hope the problem is fixed.
![image](https://user-images.githubusercontent.com/67466982/200190923-ee10fb12-daee-428e-89fe-f80d834b7331.png)

**Comment by CamKem** [comment]
Thanks, issue solved.

For reference, it wasn't the code . path in the app, it was related to having code stored inside a folder in apps.
It turns out that the Deck app doesn't like vscode being in a sub folder.

I moved it to the base applications folder and it works fine.
