### ISSUE TITLE
Unable to add existing Laravel projects

### ISSUE THREAD

**Issue by Kyzegs** [sfx101/deck#57]
The description of the project path indicates the possibility of adding existing project paths. But whenever I set the project path to an existing folder with a Laravel project, it returns the error "The selected project path is not empty, select an empty path."

**Comment by sfx101** [comment]
Hi @Kyzegs , thanks for trying out DECK. You might be using the Windows version. In Windows, the file sync from the host machine to the WSL path is extremely slow. That is why DECK requires an empty folder to begin with when creating a project. However, you could copy and paste your existing codebase into the selected path before starting the project. That way, it won't install Laravel and skip the download.

**Comment by irman** [comment]
@sfx101 maybe we could select and existing project path from the \\wsl$\ path instead since my projects are already in wsl$ since I already used to lando/docker development. PHPStorm supports it too. 
![image](https://user-images.githubusercontent.com/6107943/190378714-45342195-b392-4f91-b703-f6f5d9eb5749.png)
