### ISSUE TITLE
How can we contribute custom templates?

### ISSUE THREAD

**Issue by tylerssn** [sfx101/deck#92]
Would love to see support for Platform.sh configuration files. Is there any way or the community to contribute templates?

**Comment by sfx101** [comment]
Hi @tylerssn Yes. I didn't get a chance to add contributing guidelines to the new version release but here's something you can use to get started for templates, https://github.com/sfx101/deck/blob/v4.0.0/CONTRIBUTING.md
Please feel free with any questions, ty.

**Comment by sfx101** [comment]
Also, here's a document for creating custom stacks https://get-deck.com/docs/advanced/creating-custom-stack

**Comment by Subhajit9836** [comment]
Hi @tylerssn 

Did the solutions provided by @sfx101 help you solve the custom template creation query you were having? 

We may need to close this ticket in the next 48 hours. So, I request you to inform us about the status of your query. :-)

Thanks

**Comment by dpatou** [comment]
Since i've been trying to access the documentation and the website is down + the doc doesn't seem to be somewhere on that repo (too bad), pasting here what I got from google's cache of the documentation, in case it helps anyone : 

Creating a custom stack
Template for creating custom stacks in DECK
- Clone this repo `git clone https://github.com/deck-app/custom-stack/`
- If you have DECK installed already then open file `~/.deck/storage/custom-stacks.json` in the code editor
- Copy & paste the contents below inside `"stacks": []`

```
{
  "@AppID": "custom-20012021",
  "@AppName": "Custom stack",
  "@Logo": "https://get-deck.com/wp-content/uploads/2022/03/custom-stack.png",
  "@Description": "this is a custom stack",
  "@LocalPath": "/path/to/cloned/repo"
}
```
